[package]
name = "jutsu-context"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
pinocchio.workspace = true
jutsu-accounts.workspace = true
jutsu-errors.workspace = true
jutsu-utility.workspace = true