[package]
name = "hayabusa-token2022"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Hayabusa Token2022 program interface"
publish = false

[dependencies]
